---
title: "Home"
---

## Inference

### Likelihood Ratio and Likelihood

*  [Likelihood Ratio for fully specified models, discrete data](likelihood_ratio_simple_models.html)
*  [Likelihood Ratio for fully specified models, continuous data](likelihood_ratio_simple_continuous_data.html)
*  Likelihood Ratios: Examples and Pitfalls
    -  [Examples and Pitfalls](likelihood_do_dont.html)
    -  [Example: LRs must be computed on same data](LR_error.html)

*  [Likelihood Ratios: how big is convincing?](LR_and_BF.html)
*  [Likelihood Ratios: Wilks's Theorem](wilks.html)
*  [The Likelihood Function](likelihood_function.html)
*  [Asymptotic Normality of MLE](asymptotic_normality_mle.html)

### Bayesian Inference

*  [Bayesian inference for comparing two fully-specified models](LR_and_BF.html)
*  [Bayesian inference for comparing multiple fully-specified models](bayes_multiclass.html)
*  [Bayesian inference for a continuous parameter: analytic calculation](bayes_beta_binomial.html)
*  [Bayesian inference for a continuous parameter: summarizing the posterior](summarize_interpret_posterior.html)
*  [Bayesian inference for a continuous parameter: conjugacy](bayes_conjugate.html)
*  [Bayesian inference for multiple independent parameters](bayes_independent.html)


*  [Bayesian inference for normal mean (known variance)](shiny_normal_example.html)


### Frequentist vs Bayesian Inference

* [The difficulty calibrating p values](pvalue_difficult_calibrate_example.html)
* [Relationship between Bayes Factor and p value](BF_and_pvalue.html)
* [Conditional coverage of a standard normal CI](CI_conditional_coverage.html)


### Decision Theory

*  [Making a decision under uncertainty: the two class problem](decisions_costs_intro.html)

### Mixture Models

*  [Introduction to Mixture Models](intro_to_mixture_models.html)
*  [Introduction to EM: Gaussian Mixture Models](intro_to_em.html)

### Bayesian Computation

* [Every Bayesian computation is an integral (or a sum)](integral.html)
* [Importance sampling](Importance_sampling.html)

### Markov Chain Monte Carlo

* [Introduction to Gibbs Sampling](gibbs1.html)
* [Gibbs Sampling for a univariate normal mixture](gibbs2.html)

* [Simple examples of Metropolis--Hastings algorithm](MH-examples1.html)

## Distributions

* [The Beta Distribution](beta.html)
* [The Dirichlet Distribution](dirichlet.html)

## Stochastic Processes

### Discrete-Time Markov Chains
*  [Discrete-Time Markov Chains: Introduction](markov_chains_discrete_intro.html)

*  [Discrete-Time Markov Chains: Finding the Stationary Distribution via solution of the global balance equations](stationary_distribution.html)

*  [Discrete-Time Markov Chains: Finding the Stationary Distribution via eigendecomposition](markov_chains_discrete_stationary_dist.html)

*  [Simulating Discrete-Time Markov Chains: An Introduction](simulating_discrete_chains_1.html)

*  [Simulating Discrete-Time Markov Chains: Limiting Distributions](simulating_discrete_chains_2.html)

### Poisson Processes

*  [Poisson Processes: Thinning with time-dependent probabilities](poisson_process_time_dependent_thinning.html)
*  [Poisson Process: The Limiting Case of the Bernoulli Process](bernoulli_poisson_process.html)

### Methods for sampling non-standard distributions

*  [Inverse Transform Sampling](inverse_transform_sampling.html)


### Multivariate Normal

* [Multivariate Normal](mvnorm.html)
* [Normal Markov Chain](normal_markov_chain.html)

## Population Genetics

* [Wright-Fisher Model](wright_fisher_model.html)
* [Wright-Fisher Model Approximations](approx_wright_fisher_model.html)
